name: Build Frontend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build project
        run: |
          cd frontend
          npm run build

      - name: Zip dist folder
        run: |
          cd frontend/dist
          zip -r ../../dist.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: dist.zip
